parameters:
    scheme: "tcp"
    host: "localhost"
    port: 6379
    ssl.caFile: ~
    ssl.localCert: ~
    ssl.verifyPeer: ~

    clusterType: "redis"

    parameters.standard:
        scheme: "%scheme%"
        host: "%host%"
        port: "%port%"
        ssl:
            cafile: "%ssl.caFile%"
            local_cert: "%ssl.localCert%"
            verify_peer: "%ssl.verifyPeer%"

    defaultQueueKey: null

services:
    client:
        class: Predis\Client
        arguments:
            - "%parameters.standard%"

    clientFactory:
        class: Lexide\QueueBall\Redis\PredisClientFactory
        arguments:
            - "%parameters.standard%"
            - "%clusterType%"

    queue:
        class: Lexide\QueueBall\Redis\Queue
        arguments:
            - "@client"
            - "@lexide_queueball.messageFactory"
            - "%defaultQueueKey%"

    lexide_queueball.defaultQueue:
        aliasOf: "@queue"

