parameters:
    scheme: "tcp"
    host: "localhost"
    port: 6379
    ssl.caFile: ~
    ssl.localCert: ~
    ssl.verifyPeer: ~

    clusterType: "redis"

    parameters.standard:
        host: "%scheme%://%host%"
        port: "%port%"
        ssl:
            cafile: "%ssl.caFile%"
            local_cert: "%ssl.localCert%"
            verify_peer: "%ssl.verifyPeer%"

    defaultQueueKey: null

services:
    client:
        class: Lexide\QueueBall\Redis\LazyRedisWrapper
        factoryService: "@clientFactory"
        factoryMethod: "create"
        arguments:
            - "%parameters.standard%"

    clientFactory:
        class: Lexide\QueueBall\Redis\RedisClientFactory
        arguments:
            - "%parameters.standard%"

    queue:
        class: Lexide\QueueBall\Redis\Queue
        arguments:
            - "@client"
            - "@lexide_queueball.messageFactory"
            - "%defaultQueueKey%"

    lexide_queueball.defaultQueue:
        aliasOf: "@queue"

